---
apiVersion: v1 
kind: Service
metadata:
  name: nop-svc
  labels:
    app: nopCommerce
    tech: dotnet
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nopCommerce
  type: LoadBalancer  
        

