---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
  name: nop-pvc 
  labels:
    app: nopCommerce
    db: mysql
spec:
  storageClassName: ebs-sc
  volumeName: nop-vol    
  accessModes:
    - ReadWriteOnce
  resources:
    limits: 
      storage: 1Gi    
